backend:
  name: git-gateway
  branch: main # o la rama que uses en tu repo

media_folder: "img/uploads"     # Carpeta en el repo donde se guardan las imágenes nuevas
public_folder: "/img/uploads"   # Ruta pública para mostrarlas en la web

collections:
  - name: "site_content"
    label: "Contenido del sitio"
    files:
      # HEADER
      - label: "Header"
        name: "header"
        file: "content/header.md"
        fields:
          - { label: "Imagen de perfil", name: "header_profile_img", widget: "image" }
          - { label: "Título principal", name: "header_title", widget: "string" }
          - { label: "Subtítulo", name: "header_subtitle", widget: "string" }

      # PORTFOLIO
      - label: "Portfolio"
        name: "portfolio"
        file: "content/portfolio.md"
        fields:
          - { label: "Imagen 1", name: "portfolio_img_1", widget: "image" }
          - { label: "Imagen 2", name: "portfolio_img_2", widget: "image" }
          - { label: "Imagen 3", name: "portfolio_img_3", widget: "image" }
          - { label: "Imagen 4", name: "portfolio_img_4", widget: "image" }
          - { label: "Imagen 5", name: "portfolio_img_5", widget: "image" }
          - { label: "Imagen 6", name: "portfolio_img_6", widget: "image" }

      # ABOUT
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Título", name: "about_title", widget: "string" }
          - { label: "Texto columna 1", name: "about_text_1", widget: "markdown" }
          - { label: "Texto columna 2", name: "about_text_2", widget: "markdown" }
          - { label: "Texto del botón", name: "about_button_text", widget: "string" }
          - { label: "Enlace del botón", name: "about_button_link", widget: "string" }

      # FOOTER
      - label: "Footer"
        name: "footer"
        file: "content/footer.md"
        fields:
          - { label: "Título ubicación", name: "footer_location_title", widget: "string" }
          - { label: "Texto ubicación", name: "footer_location_text", widget: "markdown" }
          - { label: "Título redes sociales", name: "footer_social_title", widget: "string" }
          - { label: "Enlace Facebook", name: "footer_link_facebook", widget: "string" }
          - { label: "Enlace Google Plus", name: "footer_link_google", widget: "string" }
          - { label: "Enlace Twitter", name: "footer_link_twitter", widget: "string" }
          - { label: "Enlace Dribbble", name: "footer_link_dribbble", widget: "string" }
          - { label: "Título sobre", name: "footer_about_title", widget: "string" }
          - { label: "Texto sobre", name: "footer_about_text", widget: "markdown" }
          - { label: "Texto copyright", name: "footer_copy_text", widget: "string" }
